name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test_local:
    name: asdf mocked plugin test
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v2
      - run: scripts/test.bash
  plugin_test:
    name: asdf plugin test
    if: false # Disabling this for now because its not a public repo
    strategy:
      matrix:
        os:
          - macos-latest
    needs:
      - plugin_test_local
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: datadog-static-analyzer -v
