name: Release

on:
  workflow_run:
    workflows: ["lint", "build"]
    branches: [main]
    types: 
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: simple
